<a href="https://colab.research.google.com/github/manish-anandani/Data-Science-Projects/blob/main/CrudeOil_refinery_recco_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Objectives

At the end of the experiment, we will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce
* 20 gallons of motor oil,
* 10 gallons of diesel oil, and
* 5 gallons of gasoline

Similarly, factory $B$ can produce
* 4 gallons of motor oil,
* 14 gallons of diesel oil, and
* 5 gallons of gasoline

while factory $C$ can produce
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and
* 12 gallons of gasoline

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

### Create an array

Create an array of size 2x3 with arbitrary values.

In [6]:
import numpy as np
import sympy as sy

#solve_fuel Computes the “exact” solution, x, of the well-determined, i.e., full rank, linear matrix equation ax = b.
#numpy.linalg.solve() Solve a linear matrix equation, or system of linear scalar equations.

def solve_fuel(A, b):
  x = np.ceil(np.linalg.solve(A, b))
  return x

### Create the system of Linear Equations

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

In [7]:
# Coefficients matrix
coefficients = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constants vector
constants = np.array([6600, 5100, 3100])

# Solve the system of equations
solution = np.linalg.solve(coefficients, constants)

# Round the solutions to the nearest integer
solution = np.round(solution).astype(int) #ceil

# Print the solution
print("Number of barrels: A =", solution[0], ", B =", solution[1], ", C =", solution[2])

Coef_aug = sy.Matrix([[20, 4, 4, 6600], [10, 14, 5, 5100], [5, 5, 12, 3100]])
Coef_aug.rref()

Number of barrels: A = 287 , B = 129 , C = 85


(Matrix([
 [1, 0, 0, 1149/4],
 [0, 1, 0,  515/4],
 [0, 0, 1,     85]]),
 (0, 1, 2))

Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

In [8]:
# Coefficients matrix
coefficients = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constants vector
constants = np.array([13200, 10200, 6200])

# Solve the system of equations
solution = np.linalg.solve(coefficients, constants)

# Round the solutions to the nearest integer
solution = np.round(solution).astype(int)

# Print the solution
print("Number of barrels: A =", solution[0], ", B =", solution[1], ", C =", solution[2])

# results are doubled as the output is also doubled
# AX = B
# 2(AX) = 2B
# A(2X) = 2B
# properties of linear maps - scaling and homogenity

Number of barrels: A = 574 , B = 258 , C = 170


In the updated solution, when the total demand for all products is doubled, the number of barrels required by each factory has also increased proportionally compared to the original solution.Here the number of barrels required in each case got doubled.

Mathematically, this increase in the number of barrels required can be expected because doubling the demand effectively doubles the right-hand side values of the equations. As a result, the solution values (x, y, z) need to increase to satisfy the new demand levels. This relationship between the demand and solution values is inherent in the linear equations and reflects the direct proportionality between the demand and the required production quantities.


Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

Now the system of linear equations will be

Motor oil:   20x+4y+4z=2000

Diesel oil:   10x+14y+5z=4000

Gasoline:   5x+5y+12z=4000


In [9]:
# Coefficients matrix
coefficients = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constants vector
constants = np.array([2000, 4000, 4000])

# Solve the system of equations
solution = np.linalg.solve(coefficients, constants)

# Round the solutions to the nearest integer
solution = np.round(solution).astype(int)  # ceil  x = np.ceil(np.linalg.solve(A, b))

# Print the solution
print("Number of barrels: A =", solution[0], ", B =", solution[1], ", C =", solution[2])




Number of barrels: A = 12 , B = 188 , C = 250


Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

In [10]:
# Coefficients matrix
coefficients = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constants vector
constants = np.array([2000, 4000, 4000]) + np.array([6600, 5100, 3100])

# Solve the system of equations
solution = np.linalg.solve(coefficients, constants)

# Round the solutions to the nearest integer
solution = np.round(solution).astype(int)

# Print the solution
print("Number of barrels: A =", solution[0], ", B =", solution[1], ", C =", solution[2])


# AC1 = B1
# AC2 = B2
# B1+B2 = AC1 + AC2
# B3 = A(C1+C2)
# B3 = A(C3)   => C3 = C1+C2
#linear maps property
# This can be proved by comparing the 2 outputs in code - ToDo

Number of barrels: A = 300 , B = 316 , C = 335


*Comparing this solution to the previously obtained results (without considering the additional group of distributors), we can observe that the needs of each factory have increased. This increase was expected mathematically since the total demand has increased with the inclusion of the new group of distributors. As a result, the factories require more barrels of crude oil to produce the increased quantity of products demanded by both groups.*

### AC1 = B1
### AC2 = B2
### B1+B2 = AC1 + AC2
### B3 = A(C1+C2)
### B3 = A(C3)   => C3 = C1+C2

Therefore, the mathematical conclusion we can draw is that the needs of each factory are directly proportional to the total demand. When the total demand increases, the needs of each factory also increase accordingly.

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [11]:
# Coefficients of the system of equations
coefficients = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constants of the system of equations
constants = np.array([6600, 5100, 3100])

# Solve the system of equations
solution = np.linalg.solve(coefficients, constants)

# Round the solutions to the nearest integer
solution = np.round(solution).astype(int)

print("Original Solution:")
print("Number of barrels: A =", solution[0], ", B =", solution[1], ", C =", solution[2])

# Modify coefficients by ±3%
modified_coefficients = coefficients.copy()
modified_coefficients[0, 0] *= 1.03  # Increase motor oil coefficient by 3%
modified_coefficients[1, 1] *= 0.97  # Decrease diesel oil coefficient by 3%
modified_coefficients[2, 2] *= 1.03  # Increase gasoline coefficient by 3%

# Solve the modified system of equations
modified_solution = np.linalg.solve(modified_coefficients, constants)

# Round the solutions to the nearest integer
modified_solution = np.round(modified_solution).astype(int)


print("\nModified Solution:")
print("Number of barrels: A =", modified_solution[0], ", B =", modified_solution[1], ", C =", modified_solution[2])

# Calculate percentage changes
percentage_change = (modified_solution - solution) / solution * 100

print("\nPercentage Change:")
print("Motor Oil:   {:.2f}%".format(percentage_change[0]))
print("Diesel Oil:  {:.2f}%".format(percentage_change[1]))
print("Gasoline:    {:.2f}%".format(percentage_change[2]))


Original Solution:
Number of barrels: A = 287 , B = 129 , C = 85

Modified Solution:
Number of barrels: A = 286 , B = 142 , C = 80

Percentage Change:
Motor Oil:   -0.35%
Diesel Oil:  10.08%
Gasoline:    -5.88%


In [12]:
def print_output(c):
  print('Number of barrels used by A:%d'%c[0])
  print('Number of barrels used by B:%d'%c[1])
  print('Number of barrels used by C:%d'%c[2])


a4 = np.array([[20.0, 4.0, 4.0],
              [10.0, 14.0, 5.0],
              [5.0, 5.0, 12.0]])

b4 = np.array([6600,5100,3100])
print('Original production requirement')
c4 = np.linalg.solve(a4,b4)
c4 = np.ceil(c4)
print_output(c4)

#reducing A factory output by 3%
print('reducing A factory output by 3%')
a5=a4
a5[0:3,0] = a5[0:3,0]*0.97
print(a5)
c4 = np.linalg.solve(a5,b4)
c4 = np.ceil(c4)
print_output(c4)

print('reducing B factory output by 3%')
a5[0:3,1] = a5[0:3,1]*0.97
print(a5)
c4 = np.linalg.solve(a5,b4)
c4 = np.ceil(c4)
print_output(c4)

print('reducing C factory output by 3%')
a5[0:3,2] = a5[0:3,2]*0.97
print(a5)
c4 = np.linalg.solve(a5,b4)
c4 = np.ceil(c4)
print_output(c4)

# when we start reducing the output of the factory one by one by 3%, corresponding requirement from the factory increased by 3%
print("Conclusion: when we start reducing the output of the factory one by one by 3%, corresponding output of the factory increased by 3%.\n" \
      "At the end all factories requirement is increase by 3 %")

print(" AC=B \n" \
" When A => 0.97 * A , there is corresponding increase in C => 1.03 * C,  to maintain the RHS side same as B\n" \
" 0.97 *1.03 ~ 1")

print("\nThe condition number for corffiecient matrix - this is to understand the quality of the matrix")
print(np.linalg.cond(a4))

#Since the condition number is 3 (relatively low) the coefficient matrix is well conditioned

Original production requirement
Number of barrels used by A:288
Number of barrels used by B:129
Number of barrels used by C:85
reducing A factory output by 3%
[[19.4   4.    4.  ]
 [ 9.7  14.    5.  ]
 [ 4.85  5.   12.  ]]
Number of barrels used by A:297
Number of barrels used by B:129
Number of barrels used by C:85
reducing B factory output by 3%
[[19.4   3.88  4.  ]
 [ 9.7  13.58  5.  ]
 [ 4.85  4.85 12.  ]]
Number of barrels used by A:297
Number of barrels used by B:133
Number of barrels used by C:85
reducing C factory output by 3%
[[19.4   3.88  3.88]
 [ 9.7  13.58  4.85]
 [ 4.85  4.85 11.64]]
Number of barrels used by A:297
Number of barrels used by B:133
Number of barrels used by C:88
Conclusion: when we start reducing the output of the factory one by one by 3%, corresponding output of the factory increased by 3%.
At the end all factories requirement is increase by 3 %
 AC=B 
 When A => 0.97 * A , there is corresponding increase in C => 1.03 * C,  to maintain the RHS side same as

Overall Conclusion:
Conclusion: when we start reducing the output of the factory one by one by 3%, corresponding crude oil barrels of the factory increased by 3%.

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

If Factory C is temporarily shut down by the EPA due to excessive emissions, it means that the production capacity of Factory C is unavailable. In this scenario, the company would need to adjust its production schedule to meet the original demand from distributors (6600 gallons of motor oil, 5100 gallons of diesel oil, and 3100 gallons of gasoline).

Since Factory C is not operational, it cannot contribute to the production. Therefore, the company's ability to meet the demand will be affected. The production capacity of Factories A and B alone will not be sufficient to meet the entire demand.

To determine the production schedule, we can solve the system of linear equations considering only Factories A and B. The system of equations without Factory C would be:

Motor oil: 20x + 4y = 6600

Diesel oil: 10x + 14y = 5100

Gasoline: 5x + 5y = 3100

In [13]:
#Linear equations once factory C is shut down

oils = ['motor oil','deisel oil','gasoline']
A = np.array([[20.0, 4.0],
              [10.0, 14.0],
              [5.0, 5.0]
            ])

b = np.array([6600, 5100, 3100])

print("Expected production of oils :")
for k in range(len(oils)):
  print(f"{oils[k]} = {b[k]}")
print()

# Option 1 - Solve for x and y using the least squares method
x, residuals, _, _ = np.linalg.lstsq(A, b, rcond=None)
x = np.ceil(x)
# Display the solution for the over determined system
print("Solution 1 : Using least squares: Number of barrels used by factory A, and B")
print(x)
print()
for i in range(len(oils)):
  print(f"Amount of {oils[i]} produced")
  print(A[i][0]*x[0]+A[i][1]*x[1])

print("\nThe motor oil and deisel oil produced are ok - gasoline needs to be produced more")
print()

# Option 2 - Solve for x and y using any 2 equations

for i in range(A.shape[0]): # for combinations of 2 equations
  # print(A.shape[0], i)
  if (i < A.shape[0]-1):
    A1 = A[i:i+2]
    b1 = b[i:i+2]
  if (i == A.shape[0]-1):
    A1 = A[[0,-1],:]
    b1 = [b[0]] + [b[-1]]
  # print(A1, b1)

  x = solve_fuel(A1, b1)
  # Display the solution
  print(f"Solution {i+2} : Using 2 equations of 3: Number of barrels used by factory A, and B")
  print(x)

  for j in range(len(oils)):
    print(f"Amount of {oils[j]} produced")
    print(A[j][0]*x[0]+A[j][1]*x[1])
  print()

print("\nConclusion - Solution 1 with least square method fits best when compared if any combination of 2 equations is used to solve for y and z")



Expected production of oils :
motor oil = 6600
deisel oil = 5100
gasoline = 3100

Solution 1 : Using least squares: Number of barrels used by factory A, and B
[300. 169.]

Amount of motor oil produced
6676.0
Amount of deisel oil produced
5366.0
Amount of gasoline produced
2345.0

The motor oil and deisel oil produced are ok - gasoline needs to be produced more

Solution 2 : Using 2 equations of 3: Number of barrels used by factory A, and B
[300. 150.]
Amount of motor oil produced
6600.0
Amount of deisel oil produced
5100.0
Amount of gasoline produced
2250.0

Solution 3 : Using 2 equations of 3: Number of barrels used by factory A, and B
[ 895. -275.]
Amount of motor oil produced
16800.0
Amount of deisel oil produced
5100.0
Amount of gasoline produced
3100.0

Solution 4 : Using 2 equations of 3: Number of barrels used by factory A, and B
[258. 363.]
Amount of motor oil produced
6612.0
Amount of deisel oil produced
7662.0
Amount of gasoline produced
3105.0


Conclusion - Solution 1 with 

In [14]:
Prodtable9 = np.array([[20, 4],
                        [10, 14],
                        [5, 5]])


Output9 = np.array([6600, 5100, 3100])

Barrles9 = np.linalg.lstsq(Prodtable9, Output9, rcond=None)[0]

Barrles9 = np.round(Barrles9).astype(int)


print("If Factory C shuts down and complete production is handled by Factory A and Factory B")
print("FactA9 barrel requirement:", Barrles9[0])
print("FactB9 barrel requirement:", Barrles9[1])

If Factory C shuts down and complete production is handled by Factory A and Factory B
FactA9 barrel requirement: 299
FactB9 barrel requirement: 168


### Buying another plant

####(Note the following given information. You will see questions in continuation to this, in the subsequent sections)

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [15]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w],
                   [10, 14, 5, 8500-5*w],
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied (1 point)

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [16]:
# YOUR CODE HERE
A_paraffin= (195/4)*3
B_paraffin= (1325/4)*5
C_and_D_paraffin=675*2
Total_paraffin=A_paraffin+B_paraffin+C_and_D_paraffin
print(Total_paraffin)

3152.5


In [17]:
NewFactoryD = np.array([[20, 4, 4, 4],
                        [10, 14, 5, 5],
                        [5, 5, 12, 12]])


Output10 = np.array([5000, 8500, 10000])



Barrelreq10, residuals, _, _ = np.linalg.lstsq(NewFactoryD, Output10, rcond=None)
Barrelreq10 = np.round(Barrelreq10).astype(int)

print("Barrel Requirement with New Factory D:")
print("FactoryA10:", Barrelreq10[0])
print("FactoryB10:", Barrelreq10[1])
print("FactoryC10:", Barrelreq10[2])
print("FactoryD10:", Barrelreq10[3])

#Barrel Requirement with New Factory D:
A10: 49
B10: 331
C10: 338
D10: 338

#Paraffin outputcalculation
FactoryA10Paraffin = 49*3
FactoryB10Paraffin = 331*5
FactoryC10Paraffin = 338*5
FactoryD10Paraffin = 338*5
TotalParaffin10 = (49 * 3) + (331 * 5) + (338 * 2) + (338 * 2)

print("Factory A10 Paraffin output:", FactoryA10Paraffin, "galons")
print("Factory B10 Paraffin output:", FactoryB10Paraffin, "galons")
print("Factory C10 Paraffin output:", FactoryC10Paraffin, "galons")
print("Factory D10 Paraffin output:", FactoryD10Paraffin, "galons")
print("Total Paraffin 10:", TotalParaffin10, "galons")

Barrel Requirement with New Factory D:
FactoryA10: 49
FactoryB10: 331
FactoryC10: 338
FactoryD10: 338
Factory A10 Paraffin output: 147 galons
Factory B10 Paraffin output: 1655 galons
Factory C10 Paraffin output: 1690 galons
Factory D10 Paraffin output: 1690 galons
Total Paraffin 10: 3154 galons


### Selling the first plant (1 point)

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [18]:
import sympy as sy

# Create symbols for variables y, z, w
y, z, w = sy.symbols('y z w')

# Create the augmented matrix
A_aug = sy.Matrix([[4, 4, 4, 5000],
                   [14, 5, 5, 8500],
                   [5, 12, 12, 10000]])

# Compute the rref form
rref_A_aug = A_aug.rref()[0]
print(rref_A_aug)

# Extract the solutions
y_solution = rref_A_aug[0, -1]
z_solution = rref_A_aug[1, -1]
w_solution = rref_A_aug[2, -1]

# Print the solutions
print("Solution:")
print(f"y: {y_solution}")
print(f"z: {z_solution}")
print(f"w: {w_solution}")

print("The rref output shows that this set of equations does not have an unique solution - for a unique solution the first 3 columns should be identity matrix")
print("An alternate is to use the least squares method which give the best possible fit")

Matrix([[1, 0, 0, 0], [0, 1, 1, 0], [0, 0, 0, 1]])
Solution:
y: 0
z: 0
w: 1
The rref output shows that this set of equations does not have an unique solution - for a unique solution the first 3 columns should be identity matrix
An alternate is to use the least squares method which give the best possible fit


In [19]:
B = np.array([[4.0, 4.0, 4.0],
              [14.0, 5.0, 5.0],
              [5.0, 12.0, 12.0]])

B_aug = sy.Matrix([[4.0, 4.0, 4.0],
              [14.0, 5.0, 5.0],
              [5.0, 12.0, 12.0]])

c = np.array([5000, 8500, 10000])

oils = ['motor oil','deisel oil','gasoline']

print(B_aug.rref())
print("The new Linear equation matrix is rank deficiet and hence cannot be evaluated for a unique solution")
print("\nUsing least squares method")

x8, residuals, _, _ = np.linalg.lstsq(B, c, rcond=None)
x8 = np.ceil(x8)
# x8 = np.linalg.solve(B, c)
# # Display the solution
print("Solution : Total requirement of barrels for Factories B, C and D")
print(x8)
print()

for j in range(len(oils)):
  print(f"Amount of {oils[j]} produced")
  print(B[j][0]*x8[0]+B[j][1]*x8[1]+B[j][2]*x8[2])

(Matrix([
[1, 0,   0],
[0, 1, 1.0],
[0, 0,   0]]), (0, 1))
The new Linear equation matrix is rank deficiet and hence cannot be evaluated for a unique solution

Using least squares method
Solution : Total requirement of barrels for Factories B, C and D
[370. 348. 348.]

Amount of motor oil produced
4264.0
Amount of deisel oil produced
8660.0
Amount of gasoline produced
10202.0


Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [20]:
B = np.array([[4.0, 4.0, 4.0],
              [14.0, 5.0, 5.0],
              [5.0, 12.0, 12.0]])

B_aug = sy.Matrix([[4.0, 4.0, 4.0, 6600],
              [14.0, 5.0, 5.0, 5100],
              [5.0, 12.0, 12.0, 3100]])

c = np.array([6600, 5100, 3100])

print(B_aug.rref())
print("The new Linear equation matrix is rank deficiet and hence cannot be evaluated for a unique solution")

print("\nTrying least squares method")
x9, residuals, _, _ = np.linalg.lstsq(B, c, rcond=None)
x9 = np.ceil(x9)
# x8 = np.linalg.solve(B, c)
# # Display the solution
print("Solution : Total requirement of barrels for Fact B, C and D with revised demand")
print(x9)
print()

for j in range(len(oils)):
  print(f"Amount of {oils[j]} produced")
  print(B[j][0]*x9[0]+B[j][1]*x9[1]+B[j][2]*x9[2])

(Matrix([
[1, 0,   0, 0],
[0, 1, 1.0, 0],
[0, 0,   0, 1]]), (0, 1, 3))
The new Linear equation matrix is rank deficiet and hence cannot be evaluated for a unique solution

Trying least squares method
Solution : Total requirement of barrels for Fact B, C and D with revised demand
[353. 102. 102.]

Amount of motor oil produced
2228.0
Amount of deisel oil produced
5962.0
Amount of gasoline produced
4213.0


### Set rates for Products (1 point)

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows:

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which result in maximum total price.

Let $M$ denote the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\
4 & 14 & 5  \\
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\
66 & 64 & 68 & 68  \\
102 & 100 & 98 & 100  
\end{bmatrix}$$

In [21]:
import numpy as np

M = np.array([[20, 10, 5],
              [4, 14, 5],
              [4, 5, 12]])
R = np.array([[100, 104, 102, 96],
             [66, 64, 68, 68],
             [102, 100, 98, 100]])
result = np.matmul(M, R)
column_sum = np.sum(result, axis=0)

max_total_price = np.max(column_sum)
max_total_price_combination = np.argmax(column_sum)

best_rates = R[:, max_total_price_combination]

print ("Below are the combination of cost per barrel of production ")
print (result)
print("                   ")
print ('Maximum total price')
print (column_sum)
print("                   ")
print("Maximum Total Price: ", max_total_price)
print("Rates for Maximum Total Price: ", best_rates)

Below are the combination of cost per barrel of production 
[[3170 3220 3210 3100]
 [1834 1812 1850 1836]
 [1954 1936 1924 1924]]
                   
Maximum total price
[6958 6968 6984 6860]
                   
Maximum Total Price:  6984
Rates for Maximum Total Price:  [102  68  98]


### Marginal Cost (1 point)

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [22]:
import sympy as sym

# Define the variable x
x = sym.Symbol('x')

# Define the function C(x)
C = 0.005 * x**3 - 0.02 * x**2 + 30 * x + 5000

# Differentiate C(x) with respect to x
dC_dx = sym.diff(C, x)


# Print the result
print("dC/dx =", dC_dx)



dC/dx = 0.015*x**2 - 0.04*x + 30


In [23]:
# YOUR CODE HERE
x = 22
marginal_cost = 0.015 * x**2 - 0.04 * x + 30
print(marginal_cost)


36.38


### Marginal Revenue (1 point)

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [24]:
# YOUR CODE HERE
# Define the symbolic variable
x = sy.Symbol('x')

#Define the function
R_x = 3*x**2 + 36*x + 5

# Define the derivative of the polynomial
gradient = sy.diff(R_x, x)
print(sy.latex(gradient))

# Evaluate the derivative at x = 22
x_value = 28
gradient_value = gradient.subs(x, x_value)

# Display the value of the gradient at x = 22
print("Value of the gradient at x = 28:")
print(round(gradient_value,2))


6 x + 36
Value of the gradient at x = 28:
204


### Pouring crude oil in tank (1 point)

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of crude oil is increasing in the tank, and
* the height of crude oil in tank after 2 hours.

V = πr^2h

where V is the volume, r is the radius, and h is the height of the cylinder.

Given that the radius is 10 meters and the rate of change of volume is 314 cubic meters per hour, we can differentiate the volume equation with respect to time (t) to find the rate of change of height (dh/dt):

dV/dt = πr^2 * dh/dt

Simplifying, we have:

314 = π * (10^2) * (dh/dt)

Now we can solve for dh/dt, which represents the rate at which the height of crude oil is increasing:

dh/dt = 314 / (π * 100)

To find the height of the crude oil in the tank after 2 hours, we can integrate dh/dt with respect to t:

h = ∫(314 / (π * 100)) dt

Integrating, we have:

h = (314 / (π * 100)) * t + C

where C is the constant of integration.

Now we can plug in t = 2 hours to find the height of the crude oil after 2 hours.

since this will be a definite integral ,so constant of integration will be zero.

In [25]:
# YOUR CODE HERE
import math

# Calculate the rate at which the height is increasing
rate_of_increase = 314 / (math.pi * 100)
print("Rate of increase of height:", rate_of_increase, "meters per hour")

# Calculate the height of the crude oil after 2 hours
t = 2  # hours
height = (314 / (math.pi * 100)) * t
print("Height of crude oil after 2 hours:", height, "meters")


Rate of increase of height: 0.9994930426171027 meters per hour
Height of crude oil after 2 hours: 1.9989860852342054 meters


In [26]:
v = sy.Symbol('v')
r = 10
h = 1/(np.pi*r**2)*v

#rate_of_change_of_height_wrt_vol = dh/dv
dhdv = sy.diff(h, v)
print(f"The rate at which the height of crude oil is increasing wrt Vol is : {round(dhdv,5)} meter square")

#rate_of_change_of_vol_wrt_time = dv/dt
dvdt = 314

#multiple dh/dv * dv/dt = dh/dt - rate of change of height wrt to time = dh/dt
dhdt = dhdv * dvdt
print(f"The rate at which height of crude oil is increasing wrt time : {round(dhdt)} meter/hour")

t = 2
height = t * dhdt
print(f"Hieght of crude oil in tank after {t} hours is : {round(height)} meters")

The rate at which the height of crude oil is increasing wrt Vol is : 0.00318 meter square
The rate at which height of crude oil is increasing wrt time : 1 meter/hour
Hieght of crude oil in tank after 2 hours is : 2 meters
